### ISSUE TITLE
クエリ・テーブル定義

### ISSUE THREAD

**Issue by YutaUra** [ycu-engine/ycu-schedule#19]
# クエリ
- お知らせ
    - 全て
    - 個別
- 講義
    - 曜日・時間割別
    - 自分の登録している物一覧
- ユーザー
    - ユーザーIDでデータを取得

# エンティティ

### クエリ
- IDでの個別
- 全て（作成日順）

### データ
```yaml
id: string
type: 'news'
createdAt: timestamp
updatedAt: timestamp
title: string
content: string
```

### スキーマ

```yaml
getById:
    PK: id
sortByCreatedAt:
    PK: type
    SK: createdAt
```

### クエリ
- 曜日・時間割別
- 講義コードでの一覧

### データ

```yaml
id: string
code: string
type: 'course'
week: number
period: number
name: string
teacher: string
term: string
target: string
isRemote: bool
zoomUrl: string
classRoom: string
```

### スキーマ
```yaml
getByWeekPeriod:
    PK: type
    SK: week#period#code
getByCode:
    PK: type
    SK: code#week#period
```

### クエリ
- ユーザーIDごとに取得

### データ
```yaml
id: string
type: 'user'
course:
    '1#1': string
     # ...
    '7#7': string
```

### スキーマ

```yaml
getById:
    PK: id
```

# テーブル定義
```yaml
- Base
    PK:
        News: id
        Course: id
        User: id
- GSI1
    PK:
        News: type
        Course: type
    SK:
        News: createdAt
        Course: week#period#code
    LSI
        - SK:
            Course: code#week#period
```
